### ISSUE TITLE
Unsupported Java 8 syntax

### ISSUE THREAD

**Issue by jejung** [smallrye/jandex#32]
The following code fails with IllegalArgumentException:

```
public class Main { 

    public static <T> T[] producer(T... ts){
        return ts;
    }

    public static <T> void consumer(Supplier<? extends T> objs){
    }

    public static void main(String[] args) throws IOException {
        consumer(Main::producer);
        new Indexer().index(Main.class.getClassLoader().getResourceAsStream("com/test/Main.class"));
    }
}
```

The full stack trace is:

>  Exception in thread "main" java.lang.IllegalArgumentException: Expected character '^' at position 2
>     at org.jboss.jandex.GenericSignatureParser.expect(GenericSignatureParser.java:262)
>     at org.jboss.jandex.GenericSignatureParser.parseMethodSignature(GenericSignatureParser.java:298)
>     at org.jboss.jandex.Indexer.parseMethodSignature(Indexer.java:971)
>     at org.jboss.jandex.Indexer.applySignatures(Indexer.java:958)
>     at org.jboss.jandex.Indexer.index(Indexer.java:1449)
>     at com.test.Main.main(Main.java:29)

[Here is](https://github.com/wildfly/jandex/files/435504/jandex-test.zip) a simple test project, hope this helps.

**Comment by n1hility** [comment]
Interesting, what java compiler and version are you using?

**Comment by n1hility** [comment]
The reason I ask is that your example seems to contain a class file that violates the VM spec. Your not supposed to be able to return a type argument, so it looks like a compiler bug. I'm trying to figure out if I need  special handling if its a widespread issue, or if its only a specific compiler version with the problem.

private static ? extends java.lang.Object[] lambda$0();
    descriptor: ()[Ljava/lang/Object;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Signature: #64                          // ()+[Ljava/lang/Object;
    Code:
      stack=1, locals=0, args_size=0
         0: iconst_0
         1: anewarray     #3                  // class java/lang/Object
         4: invokestatic  #65                 // Method producer:([Ljava/lang/Object;)[Ljava/lang/Object;
         7: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature

**Comment by jejung** [comment]
I was compiling and running from eclipse, I tried to reproduce the problem out of eclipse but without success, so I think the problem may be with the eclipse compiler, can you confirm it?

Eclipse details:
> Eclipse Java EE IDE for Web Developers.
>
> Version: Neon Release (4.6.0)
> Build id: 20160613-1800

**Comment by Ladicek** [comment]
Please provide actionable information. I take bytecode parsing issues very seriously, but I need an actual reproducer. A Java (or Kotlin, or Scala, or Groovy, or whatever) source code is enough, as is a JAR file on Maven Central or similar.

**Comment by RoiSoleil** [comment]
First it's in Eclipse, I don't have any problem when compiling the code with javac.
I identified the exact line on my code that produces the "bug". Now I'm trying to make a small sample snippet and I will open a bug in Eclipse JDT.

**Comment by Ladicek** [comment]
The entire Jandex test suite runs with JDT on each pull request (or it _should_, at least :-) ). If there's a way to reproduce the problem with a small piece of Java source code, even if javac works just fine, I'd love to add it to the Jandex test suite. Thanks for your work on the reproducer!

**Comment by RoiSoleil** [comment]
I did managed to reproduce it with Eclipse JDT, you can see a sample code in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/756

**Comment by Ladicek** [comment]
Thank you! I managed to simplify your reproducer a little bit more (see the JDT issue) and I can add a test to the Jandex test suite for this.
